version = "1.0"

[metadata]
author_name = "Piotr Migdal"
author_email = "piotr.migdal@quesma.com"
difficulty = "easy"
tags = ["crypto", "python"]
description = "Decrypt a ROT-cipher message"

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 4096
storage_mb = 10240
