version = "1.0"

[metadata]
author_name = "Przemyslaw Hejman"
author_email = "przemyslaw.hejman@quesma.com"
difficulty = "easy"
tags = ["trivial", "golang"]
description = "An example compilation task"

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 4096
storage_mb = 10240
